FROM python:3.8-slim

WORKDIR /surf_app

COPY requirements.txt ./
COPY app.py ./
COPY libs.py ./
COPY server_params.py ./
COPY config.py ./
COPY main.py ./

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "main.py"]
